import 'dotenv/config';
import cron from 'node-cron';
import axios from 'axios';
import { createMarket } from './services/marketService.js';

// Auto-create markets like "Will BTC close above X today?"
async function bootstrap() {
  const now = Date.now();
  const end = now + 24*60*60*1000;
  createMarket({
    name: 'BTC above $60k today?',
    description: 'Auto-generated by Reflector feed',
    outcomes: ['Yes', 'No'],
    startTime: now,
    endTime: end,
    createdBy: 'system'
  });
  console.log('Seed auto-market created');
}

cron.schedule('0 */6 * * *', async () => {
  console.log('cron: would check Reflector and create new markets if thresholds crossed...');
});

bootstrap();
