// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kkehvvfmcjsqitxkkmts.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtrZWh2dmZtY2pzcWl0eGtrbXRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NjQyMTEsImV4cCI6MjA3MjM0MDIxMX0.69fEHRmdVFg8FJ6oBvgD1glnJe5u1ds1jy8SAOLyx8Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});